poller_phx/lib/poller_phx_web/router.ex
defmodule PollerPhxWeb.Router do
  use PollerPhxWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PollerPhxWeb.Plugs.Auth)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(PollerPhxWeb.Plugs.Auth)
  end

  scope "/", PollerPhxWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
  end

  scope "/auth", PollerPhxWeb do
    pipe_through(:browser)

    get("/login", AuthController, :new)
    post("/login", AuthController, :create)
    delete("/logout", AuthController, :delete)
  end

  scope "/areas", PollerPhxWeb do
    pipe_through([:browser, :valid_user, :admin_user])

    resources("/", AreaController, except: [:show])
    resources("/:area_id/questions", QuestionController, except: [:show])
    resources("/:area_id/questions/:question_id/choices", ChoiceController, except: [:show])
  end

  # Other scopes may use custom stacks.
  scope "/api", PollerPhxWeb.Api do
    pipe_through(:api)

    get("/areas", AreaController, :index)
    get("/areas/:area_id", AreaController, :show)
    get("/areas/:area_id/questions", QuestionController, :index)
    get("/questions/:question_id/choices", ChoiceController, :index)
  end

  scope "/api", PollerPhxWeb.Api do
    pipe_through([:api, :valid_user])

    put("/areas/:area_id/choices/:choice_id", ChoiceController, :vote)
  end

  scope "/app", PollerPhxWeb do
    pipe_through(:browser)

    get("/*path", AppController, :index)
  end
end

poller_phx/lib/poller_phx_web/controllers/api/area_controller.ex
defmodule PollerPhxWeb.Api.AreaController do
  use PollerPhxWeb, :controller

  alias PollerDal.Areas

  def index(conn, _params) do
    areas = Areas.list_areas()
    render(conn, "index.json", areas: areas)
  end

  def show(conn, %{"area_id" => area_id}) do
    area = Areas.get_area!(area_id)
    render(conn, "show.json", area: area)
  end
end

poller_phx/lib/poller_phx_web/controllers/area_controller.ex
defmodule PollerPhxWeb.AreaController do
  use PollerPhxWeb, :controller

  alias PollerDal.Areas
  alias PollerDal.Areas.Area

  def index(conn, _params) do
    areas = Areas.list_areas()
    render(conn, "index.html", areas: areas)
  end

  def new(conn, _params) do
    changeset = Areas.change_area(%Area{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"area" => area_params}) do
    case Areas.create_area(area_params) do
      {:ok, _area} ->
        conn
        |> put_flash(:info, "Area created successfully.")
        |> redirect(to: Routes.area_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def update(conn, %{"id" => id, "area" => area_params}) do
    area = Areas.get_area!(id)

    case Areas.update_area(area, area_params) do
      {:ok, _area} ->
        conn
        |> put_flash(:info, "Area updated successfully.")
        |> redirect(to: Routes.area_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", area: area, changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    area = Areas.get_area!(id)
    changeset = Areas.change_area(area)
    render(conn, "edit.html", area: area, changeset: changeset)
  end

  def delete(conn, %{"id" => id}) do
    area = Areas.get_area!(id)
    # pattern match on :ok tupple if match fails server will reset its self
    {:ok, _area} = Areas.delete_area(area)

    conn
    |> put_flash(:info, "Area deleted successfully.")
    |> redirect(to: Routes.area_path(conn, :index))
  end
end

poller_phx/lib/poller_phx_web/views/area_view.ex
defmodule PollerPhxWeb.AreaView do
  use PollerPhxWeb, :view
end

poller_phx/lib/poller_phx_web/templates/area/edit.html.eex
<h1>Edit Area</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.area_path(@conn, :update, @area)) %>

poller_phx/lib/poller_phx_web/templates/area/form.html.eex
<%= form_for @changeset,  @action , fn f -> %>

    <%= if @changeset.action do %>
        <div class="error">
            <P>Oops, something went wrong! Please check the errors below.</P>
        </div>
    <% end %>

    <%= label f, :name  %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>

    <div>
        <%= submit "save", class: "btn" %>
        <%= link "cancel", to: Routes.area_path(@conn, :index), class:  "btn-white"%>
    </div>

<% end %>

poller_phx/lib/poller_phx_web/templates/area/index.html.eex
<h1>Areas</h1>

<table>
    <thead>
        <tr>
            <th colspan="2"> Name</th>
        </tr>
    </thead>
    <tbody>
    <%= for area  <- @areas  do %>
        <tr>
            <td>
                <%= area.name  %>
            </td>
            <td>
                <%= link to: Routes.question_path(@conn, :index, area.id) do %>
                    <i class="fas fa-question"></i>
                <% end %>
                <%= link to: Routes.area_path(@conn, :edit, area.id) do %>
                    <i class="far fa-edit"></i>
                <% end %>
                <%= link to: Routes.area_path(@conn, :delete, area.id),
                    method: :delete,
                    data: [confirm: "Are you sure? "] do %>

                    <i class="fas fa-trash"></i>
                 <% end %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

<div>
    <%= link "New Area", to: Routes.area_path(@conn, :new), class: "btn" %>
</div>

poller_phx/lib/poller_phx_web/templates/area/new.html.eex
<h1>New Area</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.area_path(@conn, :create)) %>