poller_phx/lib/poller_phx_web/router.ex
defmodule PollerPhxWeb.Router do
  use PollerPhxWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PollerPhxWeb.Plugs.Auth)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(PollerPhxWeb.Plugs.Auth)
  end

  scope "/", PollerPhxWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
  end

  scope "/auth", PollerPhxWeb do
    pipe_through(:browser)

    get("/login", AuthController, :new)
    post("/login", AuthController, :create)
    delete("/logout", AuthController, :delete)
  end

  scope "/areas", PollerPhxWeb do
    pipe_through([:browser, :valid_user, :admin_user])

    resources("/", AreaController, except: [:show])
    resources("/:area_id/questions", QuestionController, except: [:show])
    resources("/:area_id/questions/:question_id/choices", ChoiceController, except: [:show])
  end

  # Other scopes may use custom stacks.
  scope "/api", PollerPhxWeb.Api do
    pipe_through(:api)

    get("/areas", AreaController, :index)
    get("/areas/:area_id", AreaController, :show)
    get("/areas/:area_id/questions", QuestionController, :index)
    get("/questions/:question_id/choices", ChoiceController, :index)
  end

  scope "/api", PollerPhxWeb.Api do
    pipe_through([:api, :valid_user])

    put("/areas/:area_id/choices/:choice_id", ChoiceController, :vote)
  end

  scope "/app", PollerPhxWeb do
    pipe_through(:browser)

    get("/*path", AppController, :index)
  end
end

poller_phx/lib/poller_phx_web/controllers/api/question_controller.ex
defmodule PollerPhxWeb.Api.QuestionController do
  use PollerPhxWeb, :controller

  alias PollerDal.Questions

  def index(conn, %{"area_id" => area_id}) do
    questions = Questions.list_questions_by_area_id(area_id)
    render(conn, "index.json", questions: questions)
  end
end

poller_phx/lib/poller_phx_web/controllers/question_controller.ex
defmodule PollerPhxWeb.QuestionController do
  use PollerPhxWeb, :controller

  alias PollerDal.Questions
  alias PollerDal.Questions.Question
  alias PollerDal.Areas

  def index(conn, %{"area_id" => area_id}) do
    area = Areas.get_area!(area_id)
    questions = Questions.list_questions_by_area_id(area_id)
    render(conn, "index.html", area: area, questions: questions)
  end

  def new(conn, %{"area_id" => area_id}) do
    area = Areas.get_area!(area_id)
    changeset = Questions.change_question(%Question{})
    render(conn, "new.html", changeset: changeset, area: area)
  end

  def create(conn, %{"question" => question_params, "area_id" => area_id}) do
    question_params = Map.merge(question_params, %{"area_id" => area_id})

    case Questions.create_question(question_params) do
      {:ok, _question} ->
        conn
        |> put_flash(:info, "Question created successfully.")
        |> redirect(to: Routes.question_path(conn, :index, area_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def update(conn, %{"id" => id, "question" => question_params, "area_id" => area_id}) do
    question = Questions.get_question!(id)

    case Questions.update_question(question, question_params) do
      {:ok, _area} ->
        conn
        |> put_flash(:info, "Question updated successfully.")
        |> redirect(to: Routes.question_path(conn, :index, area_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", question: question, changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id, "area_id" => area_id}) do
    area = Areas.get_area!(area_id)
    question = Questions.get_question!(id)
    changeset = Questions.change_question(question)

    render(conn, "edit.html",
      area: area,
      question: question,
      changeset: changeset
    )
  end

  def delete(conn, %{"id" => id, "area_id" => area_id}) do
    question = Questions.get_question!(id)
    # pattern match on :ok tupple if match fails server will reset its self
    {:ok, _area} = Questions.delete_question(question)

    conn
    |> put_flash(:info, "Question deleted successfully.")
    |> redirect(to: Routes.question_path(conn, :index, area_id))
  end
end

poller_phx/lib/poller_phx_web/views/question_view.ex
defmodule PollerPhxWeb.QuestionView do
  use PollerPhxWeb, :view
end

poller_phx/lib/poller_phx_web/templates/question/edit.html.eex
<h1>Edit Question for <%= @area.name%></h1>

<%= render "form.html", Map.put(assigns, :action, Routes.question_path(@conn, :update, @area.id, @question)) %>

poller_phx/lib/poller_phx_web/templates/question/form.html.eex
<%= form_for @changeset,  @action , fn f -> %>

    <%= if @changeset.action do %>
        <div class="error">
            <P>Oops, something went wrong! Please check the errors below.</P>
        </div>
    <% end %>

    <%= label f, :description  %>
    <%= text_input f, :description %>
    <%= error_tag f, :description %>

    <div>
        <%= submit "save", class: "btn" %>
        <%= link "cancel", to: Routes.question_path(@conn, :index, @area.id), class:  "btn-white"%>
    </div>

<% end %>
  

poller_phx/lib/poller_phx_web/templates/question/index.html.eex
<h1>Poll Questions for <%= @area.name%></h1>

<table>
    <thead>
        <tr>
            <th colspan="2">Description</th>
        </tr>
    </thead>
    <tbody>
        <%= for question <- @questions do %>
            <tr>
                <td>
                    <%= question.description %>
                </td>
                <td>
                    <%= link to: Routes.choice_path(@conn, :index, @area.id, question.id) do %>
                        <i class="fas fa-list-ul"></i>
                    <% end %>
                    <%= link to: Routes.question_path(@conn, :edit, @area.id, question) do %>
                        <i class="far fa-edit"></i>
                    <% end %>
                    <%= link to: Routes.question_path(@conn, :delete, @area.id, question),
                        method: :delete,
                        data: [confirm: "Are you sure? "] do %>

                        <i class="fas fa-trash"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<div>
    <%= link "New Question", to: Routes.question_path(@conn, :new, @area.id), class: "btn" %>
    <%= link "Back", to: Routes.area_path(@conn, :index), class: "btn" %>
</div>

poller_phx/lib/poller_phx_web/templates/question/new.html.eex
<h1>New Question for <%= @area.name%></h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.question_path(@conn, :create, @area.id)) %>